### ISSUE TITLE
Hamburger menu not working when viewing a review, issue persists when using "back" button

### ISSUE THREAD

**Issue by sterlingralph** [Canary-Enterprises/canary#12]
The below screencap shows

1. The hamburger menu not working when inside a review
2. When going back to the main menu via the canary logo, the menu is functional
3. However, when a review is gone to, and the browser's back button is used, the menu remains broken.

Issue duplicated on multiple devices.
https://user-images.githubusercontent.com/44482671/106342788-4a756980-6270-11eb-80a5-f5f3547bdba3.mov

**Comment by spettway** [comment]
Grant fixed this, what a beast
